name: Build and Upload to CDN

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-upload:
    env:
      CDN_URL: https://cdn.sdutacm.cn/oj-competition-side-client/homepage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        env:
          CDN_URL: https://cdn.sdutacm.cn/oj-competition-side-client/homepage
        run: npm run build
        
      - name: Display build info
        run: |
          echo "Build completed successfully!"
          echo "Build size:"
          du -sh dist/
          echo "Build contents:"
          ls -la dist/
          
      - name: Upload to Tencent COS
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -r ./dist/ oj-competition-side-client/homepage
          secret_id: ${{ secrets.COS_SECRET_ID }}
          secret_key: ${{ secrets.COS_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
          region: ${{ secrets.COS_REGION }}
          
      - name: Deployment success notification
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "📦 Project deployed to: ${{ env.CDN_URL }}"
          echo "🔗 Access URL: ${{ env.CDN_URL }}"
